config/routes.rb
Rails.application.routes.draw do
   resources :cinemas

   root 'cinemas#movies'

  
  
  get 'movies' => 'cinemas#movies'

   get 'get_movies' => 'cinemas#get_movies'
    

end

app/models/cinema.rb
class Cinema < ActiveRecord::Base
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController
  before_action :set_cinema, only: [:show, :edit, :update, :destroy]

  # GET /cinemas
  # GET /cinemas.json
  def index
    @cinemas = Cinema.all
  end


###################  Creating a class for Cinema ###########################
   class Cinema
    def initialize(title, link, duration,synopsis,image)
      @title = title
      @link = link
      @duration = duration
      @synopsis = synopsis
      @image = image
    end
    attr_reader :title
    attr_reader :link
    attr_reader :duration
    attr_reader :synopsis
    attr_reader :image
  end




def movies
  # Pull in the page
  require 'open-uri'

  doc = Nokogiri::HTML(open('https://silverbirdcinemas.com/cinema/accra/', 'User-Agent' => 'Nooby', :ssl_verify_mode => OpenSSL::SSL::VERIFY_NONE))

  # Narrow down on what we want and build the entries array
  @entries = doc.css('.entry-item')
  logger.info @entries
  @entriesArray = []


  @entries.each do |entry|

    #### Getting the movie titles and link from website and oops images too
    title = entry.css('.entry-title').text
    link = entry.css('.entry-title>a')[0]['href']
    duration = entry.css('.entry-title').text  #not using duration for this particular one
    synopsis = entry.css('.entry-title').text   #not using synopsis for this particular one
    image = entry.css('.entry-thumb img').attr('src')

    @entriesArray << Cinema.new( title, link,duration,synopsis,image)

    logger.info @entriesArray
  end

end


def get_movies
   require 'open-uri'

  url =params[:id]   ## Assumiing we fetching the id from each movie .in this case the id is the href link the website provides
  doc = Nokogiri::HTML(open(url, 'User-Agent' => 'Nooby', :ssl_verify_mode => OpenSSL::SSL::VERIFY_NONE))

  # Narrow down on what we want and build the entries array
  @entries = doc.css('.entry-info')  ## Entries contains a host of pages classes we can select from
  @entriesArray = []
  
  @entries.each do |entry|

    title = entry.css('.info-list').text
    link = entry.css('.entry-title').text
    duration = entry.css('.entry-pg').text
    synopsis =  entry.xpath('//span[@style]').text
    image = doc.css('.entry-thumb img').attr('src')   
   
    @entriesArray << Cinema.new(title , link, duration,synopsis,image)
  end

end






  # GET /cinemas/1
  # GET /cinemas/1.json
  def show
  end

  # GET /cinemas/new
  def new
    @cinema = Cinema.new
  end

  # GET /cinemas/1/edit
  def edit
  end

  # POST /cinemas
  # POST /cinemas.json
  def create
    @cinema = Cinema.new(cinema_params)

    respond_to do |format|
      if @cinema.save
        format.html { redirect_to @cinema, notice: 'Cinema was successfully created.' }
        format.json { render :show, status: :created, location: @cinema }
      else
        format.html { render :new }
        format.json { render json: @cinema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cinemas/1
  # PATCH/PUT /cinemas/1.json
  def update
    respond_to do |format|
      if @cinema.update(cinema_params)
        format.html { redirect_to @cinema, notice: 'Cinema was successfully updated.' }
        format.json { render :show, status: :ok, location: @cinema }
      else
        format.html { render :edit }
        format.json { render json: @cinema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cinemas/1
  # DELETE /cinemas/1.json
  def destroy
    @cinema.destroy
    respond_to do |format|
      format.html { redirect_to cinemas_url, notice: 'Cinema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cinema
      @cinema = Cinema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cinema_params
      # params.fetch(:cinema, {})

       params.require(:cinema).permit(:title,:link)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

 # class Entry
 #    def initialize(title, link)
 #      @title = title
 #      @link = link
 #    end
 #    attr_reader :title
 #    attr_reader :link
 #  end

 

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.fetch(:movie, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/cinemas/_form.html.erb
<%= form_for(@cinema) do |f| %>
  <% if @cinema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cinema.errors.count, "error") %> prohibited this cinema from being saved:</h2>

      <ul>
      <% @cinema.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cinemas/edit.html.erb
<h1>Editing Cinema</h1>

<%= render 'form' %>

<%= link_to 'Show', @cinema %> |
<%= link_to 'Back', cinemas_path %>

app/views/cinemas/get_movies.html.erb
<h1>Movie Details</h1>



<div>
      <table>
    
        <thead>
     <!--      <tr>


          </tr> -->
        </thead>


<ul class="lessons">
  <tbody>
  <% @entriesArray.each do |movie| %>
    <tr>
     
        <td>
          <%= image_tag(movie.image, :size => "500x500") %>
         
        </td>
        <td>
        <h4>Title</h4>
      <%= movie.link%>
       <h4>Duration</h4>
    <%=  movie.duration %>
    <h4>Actors</h4>
        <%=  movie.title %>
        <h4>Synopsis</h4>
        <%=  movie.synopsis %>
        </td>
    </tr>
  <% end %>

    <tbody>
</table>

</ul>

app/views/cinemas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cinemas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cinemas.each do |cinema| %>
      <tr>
        <td><%= link_to 'Show', cinema %></td>
        <td><%= link_to 'Edit', edit_cinema_path(cinema) %></td>
        <td><%= link_to 'Destroy', cinema, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cinema', new_cinema_path %>

app/views/cinemas/movies.html.erb
<h1>Movies Available</h1>




<ul class="lessons">
<table >
  <% @entriesArray.each_slice(7) do |movie| %>
    <tr>
      <% movie.each do |movie| %>
        <td>
          <%= image_tag(movie.image) %>
          <%= link_to movie.title , get_movies_path(:id => movie.link) %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

</ul>

app/views/cinemas/new.html.erb
<h1>New Cinema</h1>

<%= render 'form' %>

<%= link_to 'Back', cinemas_path %>

app/views/cinemas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cinema_path(@cinema) %> |
<%= link_to 'Back', cinemas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieScrap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>